-- MySQL Script generated by MySQL Workbench
-- Fri Apr  8 21:11:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TitlePageTemplater
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TitlePageTemplater` ;

-- -----------------------------------------------------
-- Schema TitlePageTemplater
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TitlePageTemplater` DEFAULT CHARACTER SET utf8 ;
USE `TitlePageTemplater` ;

-- -----------------------------------------------------
-- Table `TitlePageTemplater`.`Subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TitlePageTemplater`.`Subject` ;

CREATE TABLE IF NOT EXISTS `TitlePageTemplater`.`Subject` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Patronym` VARCHAR(45) NOT NULL,
  `IsLecturer` INT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TitlePageTemplater`.`Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TitlePageTemplater`.`Course` ;

CREATE TABLE IF NOT EXISTS `TitlePageTemplater`.`Course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Titlle` VARCHAR(45) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TitlePageTemplater`.`Departament`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TitlePageTemplater`.`Departament` ;

CREATE TABLE IF NOT EXISTS `TitlePageTemplater`.`Departament` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL COMMENT 'Кафедра',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TitlePageTemplater`.`TrainingDirection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TitlePageTemplater`.`TrainingDirection` ;

CREATE TABLE IF NOT EXISTS `TitlePageTemplater`.`TrainingDirection` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Направление подготовки',
  `Code` VARCHAR(45) NOT NULL,
  `Title` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TitlePageTemplater`.`Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TitlePageTemplater`.`Group` ;

CREATE TABLE IF NOT EXISTS `TitlePageTemplater`.`Group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  `CourseId` INT NOT NULL,
  `DepartamentId` INT NOT NULL,
  `TrainingDirectionId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Group_Course_idx` (`CourseId` ASC) ,
  INDEX `fk_Group_Departament1_idx` (`DepartamentId` ASC) ,
  INDEX `fk_Group_TrainingDirection1_idx` (`TrainingDirectionId` ASC) ,
  CONSTRAINT `fk_Group_Course`
    FOREIGN KEY (`CourseId`)
    REFERENCES `TitlePageTemplater`.`Course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Group_Departament1`
    FOREIGN KEY (`DepartamentId`)
    REFERENCES `TitlePageTemplater`.`Departament` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Group_TrainingDirection1`
    FOREIGN KEY (`TrainingDirectionId`)
    REFERENCES `TitlePageTemplater`.`TrainingDirection` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TitlePageTemplater`.`PreparationType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TitlePageTemplater`.`PreparationType` ;

CREATE TABLE IF NOT EXISTS `TitlePageTemplater`.`PreparationType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(255) NOT NULL COMMENT 'Тип подготовки (обучение или практика)',
  `From` DATETIME NOT NULL,
  `To` DATETIME NOT NULL,
  `ReportTitle` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TitlePageTemplater`.`LecturerGroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TitlePageTemplater`.`LecturerGroup` ;

CREATE TABLE IF NOT EXISTS `TitlePageTemplater`.`LecturerGroup` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `SubjectId` INT NOT NULL,
  `GroupId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LecturerGroup_Subject1_idx` (`SubjectId` ASC) ,
  INDEX `fk_LecturerGroup_Group1_idx` (`GroupId` ASC) ,
  CONSTRAINT `fk_LecturerGroup_Subject1`
    FOREIGN KEY (`SubjectId`)
    REFERENCES `TitlePageTemplater`.`Subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LecturerGroup_Group1`
    FOREIGN KEY (`GroupId`)
    REFERENCES `TitlePageTemplater`.`Group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TitlePageTemplater`.`StudentGroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TitlePageTemplater`.`StudentGroup` ;

CREATE TABLE IF NOT EXISTS `TitlePageTemplater`.`StudentGroup` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `GroupId` INT NOT NULL,
  `SubjectId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_StudentGroup_Group1_idx` (`GroupId` ASC) ,
  INDEX `fk_StudentGroup_Subject1_idx` (`SubjectId` ASC) ,
  CONSTRAINT `fk_StudentGroup_Group1`
    FOREIGN KEY (`GroupId`)
    REFERENCES `TitlePageTemplater`.`Group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StudentGroup_Subject1`
    FOREIGN KEY (`SubjectId`)
    REFERENCES `TitlePageTemplater`.`Subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TitlePageTemplater`.`Template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TitlePageTemplater`.`Template` ;

CREATE TABLE IF NOT EXISTS `TitlePageTemplater`.`Template` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Path` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TitlePageTemplater`.`Report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TitlePageTemplater`.`Report` ;

CREATE TABLE IF NOT EXISTS `TitlePageTemplater`.`Report` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `StudentId` INT NOT NULL,
  `LecturerId` INT NOT NULL,
  `TemplateId` INT NOT NULL,
  `PreparationTypeId` INT NOT NULL,
  `GroupIid` INT NOT NULL,
  `DepartamentId` INT NOT NULL,
  `TrainingDirectionId` INT NOT NULL,
  `CourseId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Report_Subject1_idx` (`StudentId` ASC) ,
  INDEX `fk_Report_Subject2_idx` (`LecturerId` ASC) ,
  INDEX `fk_Report_Template1_idx` (`TemplateId` ASC) ,
  INDEX `fk_Report_PreparationType1_idx` (`PreparationTypeId` ASC) ,
  INDEX `fk_Report_Group1_idx` (`GroupIid` ASC) ,
  INDEX `fk_Report_Departament1_idx` (`DepartamentId` ASC) ,
  INDEX `fk_Report_TrainingDirection1_idx` (`TrainingDirectionId` ASC) ,
  INDEX `fk_Report_Course1_idx` (`CourseId` ASC) ,
  CONSTRAINT `fk_Report_Subject1`
    FOREIGN KEY (`StudentId`)
    REFERENCES `TitlePageTemplater`.`Subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Report_Subject2`
    FOREIGN KEY (`LecturerId`)
    REFERENCES `TitlePageTemplater`.`Subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Report_Template1`
    FOREIGN KEY (`TemplateId`)
    REFERENCES `TitlePageTemplater`.`Template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Report_PreparationType1`
    FOREIGN KEY (`PreparationTypeId`)
    REFERENCES `TitlePageTemplater`.`PreparationType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Report_Group1`
    FOREIGN KEY (`GroupIid`)
    REFERENCES `TitlePageTemplater`.`Group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Report_Departament1`
    FOREIGN KEY (`DepartamentId`)
    REFERENCES `TitlePageTemplater`.`Departament` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Report_TrainingDirection1`
    FOREIGN KEY (`TrainingDirectionId`)
    REFERENCES `TitlePageTemplater`.`TrainingDirection` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Report_Course1`
    FOREIGN KEY (`CourseId`)
    REFERENCES `TitlePageTemplater`.`Course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TitlePageTemplater`.`Settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TitlePageTemplater`.`Settings` ;

CREATE TABLE IF NOT EXISTS `TitlePageTemplater`.`Settings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Key` VARCHAR(45) NOT NULL,
  `Value` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `TitlePageTemplater` ;

-- -----------------------------------------------------
-- Placeholder table for view `TitlePageTemplater`.`ReportVU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TitlePageTemplater`.`ReportVU` (`id` INT, `TemplateId` INT, `template` INT, `StudentId` INT, `Student` INT, `LecturerId` INT, `Lecturer` INT, `GroupId` INT, `Group` INT, `CourceId` INT, `Course` INT, `CouseType` INT, `DepartamentId` INT, `Departament` INT, `TrainingDirectionId` INT, `TrainingDirectionCode` INT, `TrainingDirection` INT, `PreparationTypeId` INT, `PreparationType` INT, `PreparationTypeReport` INT, `PreparationTypeFrom` INT, `PreparationTypeTo` INT);

-- -----------------------------------------------------
-- View `TitlePageTemplater`.`ReportVU`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TitlePageTemplater`.`ReportVU`;
DROP VIEW IF EXISTS `TitlePageTemplater`.`ReportVU` ;
USE `TitlePageTemplater`;
CREATE  OR REPLACE VIEW `ReportVU` AS
SELECT
r.id,
t.id AS TemplateId,
t.Path AS template,
stud.Id AS StudentId,
CONCAT(stud.Surname, ' ', stud.Name, ' ',stud.Patronym) AS Student,
lect.Id AS LecturerId,
CONCAT(lect.Surname, ' ', lect.Name, ' ',lect.Patronym) AS Lecturer,
g.id AS GroupId,
g.Title AS `Group`,
c.id As CourceId,
c.Titlle AS `Course`,
c.`Type` AS `CouseType`,
d.id AS DepartamentId,
d.Title AS `Departament`,
td.id AS TrainingDirectionId,
td.`Code` AS TrainingDirectionCode,
td.Title AS `TrainingDirection`,
pt.id AS PreparationTypeId,
pt.Title AS `PreparationType`,
pt.ReportTitle AS `PreparationTypeReport`,
pt.`From` AS `PreparationTypeFrom`,
pt.`To` AS `PreparationTypeTo`
FROM
report AS r
INNER JOIN template AS t ON t.id = r.TemplateId
INNER JOIN subject AS lect ON lect.id = r.LecturerId
INNER JOIN subject AS stud ON stud.id = r.StudentId
INNER JOIN `group` AS g ON g.id = r.GroupIid
INNER JOIN course AS c ON c.id = r.CourseId
INNER JOIN departament AS d ON d.id = r.DepartamentId
INNER JOIN trainingdirection AS td ON td.id = r.TrainingDirectionId
INNER JOIN preparationtype AS pt ON pt.id = r.PreparationTypeId;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
